### ISSUE TITLE
Additional xdebug settings required to get started

### ISSUE THREAD

**Issue by vmpj** [JetBrains/phpstorm-docker-images#13]
Thanks for these great images. It helped me a lot to get started quickly.

I just had some issue getting it to work with the default config though.
Adding the following additional config allowed xdebug to connect to PHPStorm without any issue.

```
RUN echo 'xdebug.remote_host=host.docker.internal' >> /usr/local/etc/php/php.ini
RUN echo 'xdebug.remote_autostart=1' >> /usr/local/etc/php/php.ini
```

I was using the setup from the image `phpstorm/php-72-apache-xdebug-27`

Should this config not be included in the images by default?

**Comment by emrzv** [comment]
Sorry for the late reply. 

> Should this config not be included in the images by default?

There are reasons that these are not included by default.
`xdebug.remote_autostart=1` is generally really inconvenient because debugging sessions would start immediately as soon as you open any page via the web server, you'll have no control over when they start. That will affect performance and also force you to keep Listening for incoming connections off until you actually want to debug.
`xdebug.remote_host=host.docker.internal` will not work on Linux, Docker doesn't have a unified way of connecting to the host machine for all platforms.
